import { Question } from './mockData';

export const ENGLISH_IELTS_QUESTIONS: Omit<Question, 'id' | 'categoryId' | 'subCategoryId'>[] = [
  { questionText: 'You must ____ an effort to improve.', options: ['do', 'make', 'have', 'take'], correctAnswerIndex: 1, explanation: 'The correct collocation is "make an effort".', timeLimitSeconds: 5 },
  { questionText: 'She is very good ____ math.', options: ['in', 'with', 'at', 'on'], correctAnswerIndex: 2, explanation: 'The correct preposition is "good at".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very bad" with a stronger word:', options: ['atrocious', 'unfortunate', 'disliked', 'upsetting'], correctAnswerIndex: 0, explanation: '"Atrocious" means exceptionally bad or displeasing.', timeLimitSeconds: 5 },
  { questionText: 'We need to ____ a decision soon.', options: ['do', 'have', 'make', 'get'], correctAnswerIndex: 2, explanation: 'The natural collocation is "make a decision".', timeLimitSeconds: 5 },
  { questionText: 'He is interested ____ learning French.', options: ['on', 'in', 'about', 'for'], correctAnswerIndex: 1, explanation: 'The correct phrase is "interested in".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very happy" with a stronger word:', options: ['ecstatic', 'content', 'pleased', 'smiling'], correctAnswerIndex: 0, explanation: '"Ecstatic" means feeling or expressing overwhelming happiness.', timeLimitSeconds: 5 },
  { questionText: 'I completely agree ____ you.', options: ['to', 'with', 'for', 'on'], correctAnswerIndex: 1, explanation: 'We say "agree with" a person.', timeLimitSeconds: 5 },
  { questionText: 'They are looking forward ____ you.', options: ['to see', 'seeing', 'to seeing', 'see'], correctAnswerIndex: 2, explanation: '"Look forward to" is always followed by a gerund (-ing).', timeLimitSeconds: 5 },
  { questionText: 'Replace "very tired" with a stronger word:', options: ['exhausted', 'sleepy', 'bored', 'lazy'], correctAnswerIndex: 0, explanation: '"Exhausted" means completely drained of energy.', timeLimitSeconds: 5 },
  { questionText: 'She is capable ____ doing it herself.', options: ['to', 'for', 'of', 'in'], correctAnswerIndex: 2, explanation: 'The correct preposition is "capable of".', timeLimitSeconds: 5 },
  { questionText: 'You should ____ attention to the teacher.', options: ['pay', 'give', 'make', 'do'], correctAnswerIndex: 0, explanation: 'The collocation is "pay attention".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very small" with a stronger word:', options: ['minuscule', 'short', 'little', 'brief'], correctAnswerIndex: 0, explanation: '"Minuscule" means extremely small or tiny.', timeLimitSeconds: 5 },
  { questionText: 'He depends heavily ____ his parents.', options: ['on', 'with', 'to', 'for'], correctAnswerIndex: 0, explanation: 'The correct preposition is "depend on".', timeLimitSeconds: 5 },
  { questionText: 'Can you ____ me a favor?', options: ['make', 'do', 'give', 'have'], correctAnswerIndex: 1, explanation: 'The collocation is "do a favor".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very big" with a stronger word:', options: ['colossal', 'tall', 'heavy', 'wide'], correctAnswerIndex: 0, explanation: '"Colossal" means extremely large.', timeLimitSeconds: 5 },
  { questionText: 'I apologize ____ being late.', options: ['to', 'for', 'on', 'about'], correctAnswerIndex: 1, explanation: 'We apologize "for" an action.', timeLimitSeconds: 5 },
  { questionText: 'She took ____ in the competition.', options: ['part', 'place', 'time', 'care'], correctAnswerIndex: 0, explanation: '"Take part" means to participate.', timeLimitSeconds: 5 },
  { questionText: 'Replace "very cold" with a stronger word:', options: ['chilly', 'freezing', 'cool', 'breezy'], correctAnswerIndex: 1, explanation: '"Freezing" means exceptionally cold.', timeLimitSeconds: 5 },
  { questionText: 'He is responsible ____ the project.', options: ['for', 'to', 'with', 'in'], correctAnswerIndex: 0, explanation: 'We are responsible "for" something.', timeLimitSeconds: 5 },
  { questionText: 'Please ____ a seat.', options: ['make', 'have', 'do', 'take'], correctAnswerIndex: 1, explanation: '"Have a seat" (or take a seat) is correct, but "have" is listed here.', timeLimitSeconds: 5 },
  { questionText: 'Replace "very hot" with a stronger word:', options: ['warm', 'boiling', 'sunny', 'humid'], correctAnswerIndex: 1, explanation: '"Boiling" is used to describe extremely hot weather.', timeLimitSeconds: 5 },
  { questionText: 'She is afraid ____ spiders.', options: ['from', 'of', 'by', 'with'], correctAnswerIndex: 1, explanation: 'The correct preposition is "afraid of".', timeLimitSeconds: 5 },
  { questionText: 'We must ____ action immediately.', options: ['make', 'take', 'do', 'have'], correctAnswerIndex: 1, explanation: 'The collocation is "take action".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very hungry" with a stronger word:', options: ['starving', 'thirsty', 'craving', 'empty'], correctAnswerIndex: 0, explanation: '"Starving" means suffering from extreme hunger.', timeLimitSeconds: 5 },
  { questionText: 'I am accustomed ____ waking up early.', options: ['with', 'in', 'to', 'for'], correctAnswerIndex: 2, explanation: 'The correct phrase is "accustomed to".', timeLimitSeconds: 5 },
  { questionText: 'He made a ____ recovery from his illness.', options: ['fast', 'swift', 'quick', 'rapid'], correctAnswerIndex: 3, explanation: '"Rapid recovery" is the strongest and most natural academic collocation here.', timeLimitSeconds: 5 },
  { questionText: 'Replace "very angry" with a stronger word:', options: ['furious', 'annoyed', 'upset', 'bothered'], correctAnswerIndex: 0, explanation: '"Furious" means extremely angry.', timeLimitSeconds: 5 },
  { questionText: 'She is jealous ____ her sister.', options: ['from', 'of', 'to', 'with'], correctAnswerIndex: 1, explanation: 'The correct preposition is "jealous of".', timeLimitSeconds: 5 },
  { questionText: 'You need to ____ the bed every morning.', options: ['do', 'make', 'fix', 'clean'], correctAnswerIndex: 1, explanation: 'The collocation is "make the bed".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very clean" with a stronger word:', options: ['spotless', 'tidy', 'neat', 'clear'], correctAnswerIndex: 0, explanation: '"Spotless" means completely clean and free from dirt.', timeLimitSeconds: 5 },
  { questionText: 'He is married ____ a doctor.', options: ['with', 'to', 'by', 'for'], correctAnswerIndex: 1, explanation: 'We say "married to" someone, not with.', timeLimitSeconds: 5 },
  { questionText: 'Let\'s ____ an experiment to test the theory.', options: ['make', 'do', 'have', 'create'], correctAnswerIndex: 1, explanation: 'We "do" or "conduct" an experiment, not make.', timeLimitSeconds: 5 },
  { questionText: 'Replace "very dirty" with a stronger word:', options: ['messy', 'filthy', 'dusty', 'muddy'], correctAnswerIndex: 1, explanation: '"Filthy" means disgustingly dirty.', timeLimitSeconds: 5 },
  { questionText: 'I am opposed ____ the new law.', options: ['with', 'against', 'to', 'for'], correctAnswerIndex: 2, explanation: 'The correct preposition is "opposed to".', timeLimitSeconds: 5 },
  { questionText: 'Please ____ my apologies.', options: ['take', 'accept', 'receive', 'have'], correctAnswerIndex: 1, explanation: 'The natural formal collocation is "accept apologies".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very fast" with a stronger word:', options: ['quick', 'rapid', 'speedy', 'brisk'], correctAnswerIndex: 1, explanation: '"Rapid" is a higher-level synonym for very fast.', timeLimitSeconds: 5 },
  { questionText: 'She is aware ____ the risks.', options: ['about', 'of', 'on', 'with'], correctAnswerIndex: 1, explanation: 'The correct phrase is "aware of".', timeLimitSeconds: 5 },
  { questionText: 'I need to ____ my hair before the party.', options: ['make', 'do', 'fix', 'have'], correctAnswerIndex: 1, explanation: 'We "do" our hair.', timeLimitSeconds: 5 },
  { questionText: 'Replace "very slow" with a stronger word:', options: ['sluggish', 'delayed', 'late', 'calm'], correctAnswerIndex: 0, explanation: '"Sluggish" implies moving very slowly, often lacking energy.', timeLimitSeconds: 5 },
  { questionText: 'He insists ____ paying for dinner.', options: ['in', 'to', 'on', 'for'], correctAnswerIndex: 2, explanation: 'The correct preposition is "insist on".', timeLimitSeconds: 5 },
  { questionText: 'She ____ a good impression on the interviewer.', options: ['did', 'made', 'had', 'gave'], correctAnswerIndex: 1, explanation: 'The collocation is "make an impression".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very important" with a stronger word:', options: ['crucial', 'useful', 'helpful', 'needed'], correctAnswerIndex: 0, explanation: '"Crucial" means of decisive importance.', timeLimitSeconds: 5 },
  { questionText: 'I am satisfied ____ the results.', options: ['for', 'by', 'with', 'on'], correctAnswerIndex: 2, explanation: 'The correct preposition is "satisfied with".', timeLimitSeconds: 5 },
  { questionText: 'You should ____ your best.', options: ['make', 'have', 'do', 'try'], correctAnswerIndex: 2, explanation: 'The collocation is "do your best".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very interesting" with a stronger word:', options: ['captivating', 'nice', 'fun', 'good'], correctAnswerIndex: 0, explanation: '"Captivating" means capable of attracting and holding interest.', timeLimitSeconds: 5 },
  { questionText: 'The museum is famous ____ its art collection.', options: ['for', 'with', 'about', 'by'], correctAnswerIndex: 0, explanation: 'The correct phrase is "famous for".', timeLimitSeconds: 5 },
  { questionText: 'He ____ advantage of the opportunity.', options: ['made', 'had', 'took', 'did'], correctAnswerIndex: 2, explanation: 'The collocation is "take advantage of".', timeLimitSeconds: 5 },
  { questionText: 'Replace "very old" with a stronger word:', options: ['ancient', 'aged', 'mature', 'past'], correctAnswerIndex: 0, explanation: '"Ancient" means belonging to the very distant past.', timeLimitSeconds: 5 },
  { questionText: 'She succeeded ____ passing the exam.', options: ['on', 'in', 'at', 'with'], correctAnswerIndex: 1, explanation: 'The correct phrase is "succeed in".', timeLimitSeconds: 5 },
  { questionText: 'They are trying to ____ a solution.', options: ['make', 'do', 'find', 'have'], correctAnswerIndex: 2, explanation: 'The common collocation is "find a solution".', timeLimitSeconds: 5 }
];
