import { Question } from './mockData';

export const ENGLISH_SPELLING_BEE_QUESTIONS: Omit<Question, 'id' | 'categoryId' | 'subCategoryId'>[] = [
  { questionText: 'Which is spelled correctly?', options: ['Accomodate', 'Acommodate', 'Accommodate', 'Acomodate'], correctAnswerIndex: 2, explanation: '"Accommodate" has two Cs and two Ms.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Embarrass', 'Embarass', 'Embarras', 'Emarass'], correctAnswerIndex: 0, explanation: '"Embarrass" has two Rs and two Ss.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Priviledge', 'Privilege', 'Privelege', 'Privelige'], correctAnswerIndex: 1, explanation: '"Privilege" is often misspelled with a "d".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Facinating', 'Fascinating', 'Fasenating', 'Fasinnating'], correctAnswerIndex: 1, explanation: '"Fascinating" comes from the word fascinate, containing an "sc".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Acknowlege', 'Acknowledgue', 'Acknowledge', 'Aknowledge'], correctAnswerIndex: 2, explanation: '"Acknowledge" contains a "d" before the "g".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Definitely', 'Definately', 'Definitly', 'Definatly'], correctAnswerIndex: 0, explanation: '"Definitely" is derived from definite, so it uses an "i".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Seperate', 'Separate', 'Seprate', 'Separette'], correctAnswerIndex: 1, explanation: 'Remember: there is a "rat" in "separate".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Weird', 'Wierd', 'Weard', 'Waird'], correctAnswerIndex: 0, explanation: '"Weird" is an exception to the "i before e" rule.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Occured', 'Occurred', 'Ocurred', 'Occurrd'], correctAnswerIndex: 1, explanation: '"Occurred" doubles both the C and the R.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Questionaire', 'Questionnaire', 'Questionnare', 'Questionnair'], correctAnswerIndex: 1, explanation: '"Questionnaire" has two Ns.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Receive', 'Recieve', 'Receve', 'Riceive'], correctAnswerIndex: 0, explanation: '"I before E except after C".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Maintainance', 'Maintenence', 'Maintenance', 'Maintanance'], correctAnswerIndex: 2, explanation: 'It is "maintenance", dropping the "ai" from maintain.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Pronuciation', 'Pronounciation', 'Pronunciation', 'Pronunciaton'], correctAnswerIndex: 2, explanation: 'There is no "o" after the first "n" in pronunciation.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Rhythm', 'Rythm', 'Rhythym', 'Rhythem'], correctAnswerIndex: 0, explanation: '"Rhythm" is notoriously hard to spell, having no standard vowels.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Millenium', 'Millennium', 'Milennium', 'Milennuim'], correctAnswerIndex: 1, explanation: '"Millennium" has two Ls and two Ns.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Cemetary', 'Cemetery', 'Cemitery', 'Cematary'], correctAnswerIndex: 1, explanation: '"Cemetery" contains three Es and no As.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Dilema', 'Dilemma', 'Dillema', 'Dillemma'], correctAnswerIndex: 1, explanation: '"Dilemma" has a double M.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Garantee', 'Guarentee', 'Guarantee', 'Gurantee'], correctAnswerIndex: 2, explanation: '"Guarantee" has a silent U.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Independant', 'Independent', 'Independint', 'Indapendent'], correctAnswerIndex: 1, explanation: '"Independent" ends in "-ent".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Maneuver', 'Manuver', 'Maneouvre', 'Manoever'], correctAnswerIndex: 0, explanation: '"Maneuver" (US spelling) has a tricky vowel sequence.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Occassion', 'Occasion', 'Ocassion', 'Occcasion'], correctAnswerIndex: 1, explanation: '"Occasion" has two Cs and only one S.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Pharoah', 'Pharaoh', 'Pharao', 'Faraoh'], correctAnswerIndex: 1, explanation: '"Pharaoh" ends with A-O-H.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Playright', 'Playwrite', 'Playwright', 'Playwite'], correctAnswerIndex: 2, explanation: '"Wright" means a maker or builder, hence playwright.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Recommend', 'Reccommend', 'Recomend', 'Reccomend'], correctAnswerIndex: 0, explanation: '"Recommend" has one C and two Ms.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Superceed', 'Supercede', 'Supersede', 'Suppercede'], correctAnswerIndex: 2, explanation: '"Supersede" is the only word in English ending in -sede.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Vacum', 'Vaccum', 'Vacuum', 'Vacume'], correctAnswerIndex: 2, explanation: '"Vacuum" has one C and two Us.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Wether', 'Weather', 'Wheather', 'Weither'], correctAnswerIndex: 1, explanation: '"Weather" refers to the atmosphere (rain, sunshine).', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Colleague', 'Coleague', 'Collaegue', 'Colleage'], correctAnswerIndex: 0, explanation: '"Colleague" has two Ls and ends in "-gue".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Concious', 'Conscious', 'Consciouse', 'Consious'], correctAnswerIndex: 1, explanation: '"Conscious" requires an "sc".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Enterpreneur', 'Entrepreneur', 'Entrapreneur', 'Entrepeneur'], correctAnswerIndex: 1, explanation: '"Entrepreneur" retains its French spelling.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Liaison', 'Liason', 'Liasion', 'Leaison'], correctAnswerIndex: 0, explanation: '"Liaison" has two Is surrounding an A.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Mischievious', 'Mischivious', 'Mischievous', 'Mischevious'], correctAnswerIndex: 2, explanation: '"Mischievous" has no "i" after the "v".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Onomatopoeia', 'Onomatopia', 'Onamatopoeia', 'Onomatopeia'], correctAnswerIndex: 0, explanation: 'It is a complex spelling from Greek roots.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Restaraunt', 'Restaurant', 'Resturant', 'Resteraunt'], correctAnswerIndex: 1, explanation: '"Restaurant" has "aur" in the middle.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Ryhme', 'Ryme', 'Rhime', 'Rhyme'], correctAnswerIndex: 3, explanation: '"Rhyme" has an "h" and a "y".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Sargeant', 'Sergeant', 'Sergent', 'Sargeint'], correctAnswerIndex: 1, explanation: '"Sergeant" has "er" instead of "ar" at the start.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Twelth', 'Twelvth', 'Twelfth', 'Twelft'], correctAnswerIndex: 2, explanation: '"Twelfth" retains an "f".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Ubiqitous', 'Ubiquitous', 'Ubiquotus', 'Ubuquitous'], correctAnswerIndex: 1, explanation: '"Ubiquitous" has a "qu" and "tou".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Zuchini', 'Zucchini', 'Zuchinni', 'Zucchinni'], correctAnswerIndex: 1, explanation: '"Zucchini" has a double C.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Absence', 'Absense', 'Abscence', 'Abcence'], correctAnswerIndex: 0, explanation: '"Absence" ends with a C.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Aquire', 'Acquire', 'Acqiure', 'Aqiure'], correctAnswerIndex: 1, explanation: '"Acquire" needs a C before the Q.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Apparant', 'Apparent', 'Aparent', 'Apparrent'], correctAnswerIndex: 1, explanation: '"Apparent" ends in "-ent".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Atheist', 'Athiest', 'Athiest', 'Atheast'], correctAnswerIndex: 0, explanation: '"Atheist" breaks the "i before e" rule.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Bizarre', 'Bizzare', 'Bizaare', 'Bizerre'], correctAnswerIndex: 0, explanation: '"Bizarre" has one Z and two Rs.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Calender', 'Calendar', 'Calander', 'Callendar'], correctAnswerIndex: 1, explanation: '"Calendar" ends in "-ar".', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Carribean', 'Caribbean', 'Caribean', 'Carribbean'], correctAnswerIndex: 1, explanation: '"Caribbean" has one R and two Bs.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Commitee', 'Committe', 'Committee', 'Comittee'], correctAnswerIndex: 2, explanation: '"Committee" has double M, double T, and double E.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Disapear', 'Dissapear', 'Disappear', 'Dissappear'], correctAnswerIndex: 2, explanation: '"Disappear" has one S and two Ps.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Ecstacy', 'Ecstasy', 'Extacy', 'Exstacy'], correctAnswerIndex: 1, explanation: '"Ecstasy" is spelled with an S.', timeLimitSeconds: 5 },
  { questionText: 'Which is spelled correctly?', options: ['Flourescent', 'Fluorescent', 'Florescent', 'Flouresent'], correctAnswerIndex: 1, explanation: '"Fluorescent" starts with "fluor-".', timeLimitSeconds: 5 }
];
